package com.iexec.core.task;

public enum TaskStatus {
    RECEIVED,
    INITIALIZING,
    INITIALIZED,
    INITIALIZE_FAILED,
    RUNNING,
    CONSENSUS_REACHED,
    REOPENING,
    REOPENED,
    REOPEN_FAILED,
    AT_LEAST_ONE_REVEALED,
    REVEALED,
    RESULT_UPLOAD_REQUESTED,
    RESULT_UPLOADING,
    RESULT_UPLOADED,
    FINALIZING,
    FINALIZED,
    FINALIZE_FAILED,
    COMPLETED,
    ERROR;

}
