name: Conventional Commit as PR title

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened

jobs:
  lint-pr-title:
    # Prevent execution on forks
    if: github.repository_owner == 'iExecBlockchainComputing'
    permissions:
      pull-requests: read
    # conventional-commits-v1.2.0
    uses: iExecBlockchainComputing/github-actions-workflows/.github/workflows/conventional-commits.yml@975de113847596617899976f67f5b5faceef0a84
