name: Conventional Commit as PR title

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened

jobs:
  lint-pr-title:
    # Prevent execution on forks
    if: github.repository_owner == 'iExecBlockchainComputing'
    permissions:
      pull-requests: read
    # conventional-commits-v1.2.1
    uses: iExecBlockchainComputing/github-actions-workflows/.github/workflows/conventional-commits.yml@7825b11bd6f0b141075368add5223c873d76a2d3
