name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release-please:
    # Prevent execution on forks
    if: github.repository_owner == 'iExecBlockchainComputing'
    # release-please-v2.2.0
    uses: iExecBlockchainComputing/github-actions-workflows/.github/workflows/release-please.yml@4e2e817b7c2dcab27a671b630e23d07f5fc94daf
    secrets: inherit
